export const ADD_SESION_DATA = 'ADD_SESION_DATA';
export const REMOVE_SESION_DATA = 'REMOVE_SESION_DATA';
export const ADD_EQUIPO_SUMINISTRO_DATA = 'ADD_EQUIPO_SUMINISTRO_DATA';
export const REMOVE_EQUIPO_SUMINISTRO_DATA = 'REMOVE_EQUIPO_SUMINISTRO_DATA';
export const ADD_FUNDOS_DATA = 'ADD_FUNDOS_DATA';
export const REMOVE_FUNDOS_DATA = 'REMOVE_FUNDOS_DATA';
export const ADD_OPERADORES_DATA = 'ADD_OPERADORES_DATA';
export const REMOVE_OPERADORES_DATA = 'REMOVE_OPERADORES_DATA';
export const DEFINIR_EQUIPO_OPERADOR = 'DEFINIR_EQUIPO_OPERADOR';
export const RESET_EQUIPO_OPERADOR = 'RESET_EQUIPO_OPERADOR';
export const DEFINIR_ESTADO_CARGA = 'DEFINIR_ESTADO_CARGA';
export const ADD_DATA_CARGAS_GENERADAS = 'ADD_DATA_CARGAS_GENERADAS';
export const REMOVE_DATA_CARGAS_GENERADAS = 'REMOVE_DATA_CARGAS_GENERADAS';
export const RESET_DATA_CARGA_DIESEL = 'RESET_DATA_CARGA_DIESEL';
export const ADD_DATA_INICIO_CARGA = 'ADD_DATA_INICIO_CARGA';
export const ADD_DATA_TERMINO_CARGA = 'ADD_DATA_TERMINO_CARGA';
export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const ACTUALIZAR_LITROS = 'ACTUALIZAR_LITROS';
export const RESETEAR_LITROS = 'RESETEAR_LITROS';
export const ADD_CARGA_REABASTECIMIENTO = 'ADD_CARGA_REABASTECIMIENTO';
export const REMOVE_CARGA_REABASTECIMIENTO = 'REMOVE_CARGA_REABASTECIMIENTO';
export const CAMBIAR_ESTADO_JORNADA = 'CAMBIAR_ESTADO_JORNADA';
export const ADD_EVENTO_JORNADA = 'ADD_EVENTO_JORNADA';
export const REMOVE_EVENTO_JORNADA = 'REMOVE_EVENTO_JORNADA';
export const DEFINIR_VALIDAR_GPS = 'DEFINIR_VALIDAR_GPS';
export const DEFINIR_FECHA_JORNADA = 'DEFINIR_FECHA_JORNADA';
export const RESET_FECHA_JORNADA = 'RESET_FECHA_JORNADA';
export const DEFINIR_ULTIMA_JORNADA = 'DEFINIR_ULTIMA_JORNADA';
export const DEFINIR_VALIDACION_JORNADA = 'DEFINIR_VALIDACION_JORNADA';

//* ESTADOS JORNADA
export const SIN_INICIAR = 1;
export const INICIO_NORMAL = 2;
export const INICIO_NO_DISPONIBLE = 3;
export const HABILITACION_CAMION = 4;
export const FIN_JORNADA = 5;

//* ESTADOS
export const SIN_CARGA = 'SIN_CARGA';
export const CARGANDO = 'CARGANDO';
